[tool.poetry]
name = "hack-assembler"
version = "0.1.0"
description = ""
authors = ["toh995 <52012721+toh995@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.11"
toolz = "^0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
